# **PANDAS**

In [ ]:
from pandas import DataFrame, Series
import pandas as pd
import numpy as np

In [ ]:
#default index
ser_1=Series([1,1,2,-3,-5,8,13])
ser_1

0     1
1     1
2     2
3    -3
4    -5
5     8
6    13
dtype: int64

In [ ]:
ser_1.values

array([ 1,  1,  2, -3, -5,  8, 13])

no matter how many external indexes we create, an internal index will always be created

In [ ]:
#custom index
ser_2=Series([1,1,2,-3,-5],index=['a','b','c','d','e'])
ser_2

a    1
b    1
c    2
d   -3
e   -5
dtype: int64

In [ ]:
ser_3=Series([1,2,3,4,5], index=["abc",'def','ghi','jkl','mno'])
ser_3

abc    1
def    2
ghi    3
jkl    4
mno    5
dtype: int64

In [ ]:
ser_2[1]==ser_2["b"]

<ipython-input-11-b42f09e0d105>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser_2[1]==ser_2["b"]

True

In [ ]:
ser_2[['c','a','b']]

c    2
a    1
b    1
dtype: int64

In [ ]:
ser_2[ser_2>0]

a    1
b    1
c    2
dtype: int64

In [ ]:
ser_2*2

a     2
b     2
c     4
d    -6
e   -10
dtype: int64

In [ ]:
np.exp(ser_2)

a    2.718282
b    2.718282
c    7.389056
d    0.049787
e    0.006738
dtype: float64

In [ ]:
dict_1={'foo':100, 'bar':200, 'baz':300}
ser_4=Series(dict)
ser_4

foo    100
bar    200
baz    300
dtype: int64

In [ ]:
index=['foo','bar','baz','qux']
ser_5=Series(dict_1,index=index)
ser_5

foo    100.0
bar    200.0
baz    300.0
qux      NaN
dtype: float64

isnull will check if there are any null values in the series

In [ ]:
pd.isnull(ser_5)

foo    False
bar    False
baz    False
qux     True
dtype: bool

In [ ]:
ser_4+ser_5

bar    400.0
baz    600.0
foo    200.0
qux      NaN
dtype: float64

In [ ]:
ser_5.name='foobarbaz'
ser_5.index.name='label'
ser_5

label
foo    100.0
bar    200.0
baz    300.0
qux      NaN
Name: foobarbaz, dtype: float64

In [ ]:
ser=Series([10,15,18,12,20,9], index=[5,8,12,0,1,7])
ser

5     10
8     15
12    18
0     12
1     20
7      9
dtype: int64

*   loc works with custom indexes
*   iloc works with internal indexes
*   loc also includes the first and last index
*   List item
*   List item

In [ ]:
ser.loc[0:1]

0    12
1    20
dtype: int64

In [ ]:
ser.iloc[0:1]

5    10
dtype: int64

In [ ]:
ser.iloc[0]

10

In [ ]:
ser.loc[0]

12

**DATAFRAME**

In [ ]:
data_1={'state': ['VA', 'VA', 'VA', 'MD', 'MD',],
        'year': [2012, 2013, 2014, 2015, 2016],
        'pop': [5.0, 5.1, 5.2, 4.0, 4.1]}
df_1=DataFrame(data_1)
df_1

  state  year  pop
0    VA  2012  5.0
1    VA  2013  5.1
2    VA  2014  5.2
3    MD  2015  4.0
4    MD  2016  4.1

In [ ]:
df_1['state']

0    VA
1    VA
2    VA
3    MD
4    MD
Name: state, dtype: object

In [ ]:
df_1.state

0    VA
1    VA
2    VA
3    MD
4    MD
Name: state, dtype: object

In [ ]:
#wap in python to print the series of prime numbers from 1 to 300 and print in series
l=[]
for i in range(1,301):
    if i>1:
        for j in range(2,i//2+1):
            if i%j==0:
                break
        else:
            l.append(i)
primes=pd.Series(l)
primes

0       2
1       3
2       5
3       7
4      11
     ...
57    271
58    277
59    281
60    283
61    293
Length: 62, dtype: int64

In [ ]:
#fibonacci
a,b=0,1
l=[]
while a<100:
    l.append(a)
    a,b=b,a+b
fibonaccis=Series(l)
fibonaccis

0      0
1      1
2      1
3      2
4      3
5      5
6      8
7     13
8     21
9     34
10    55
11    89
dtype: int64

In [ ]:
#wap to add all the numbers in a user defined list of 20 elements and find min and max amongst that list without using functions
l=[int(x) for x in input("Enter 20 numbers: ").split()]
min=l[0]
sum=0
max=l[0]

for i in l:
    sum+=i
    if i<min:
        min=i
    if i>max:
        max=i

print("Sum: ",sum)
print("Min: ",min)
print("Max: ",max)

Enter 20 numbers: 1 2 3 45 6
Sum:  57
Min:  1
Max:  45

In [ ]:
l=[]
s=0
for i in range(1,21):
    l.append(int(input("Enter number: ")))
    s+=l[i-1]
print("Sum: ",s)

Enter number: 1
Enter number: 2
Enter number: 3
Enter number: 4
Enter number: 5
Enter number: 6
Enter number: 7
Enter number: 8
Enter number: 9
Enter number: 0
Enter number: 1
Enter number: 2
Enter number: 3
Enter number: 4
Enter number: 5
Enter number: 6
Enter number: 7
Enter number: 8
Enter number: 9
Enter number: 0
Sum:  90